import { Box, Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/index";
import GlowingButtonPrimary, {
  GlowingButton,
} from "../components/GlowingButton";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Jalaj</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={styles.content}>
        <Typography color="text.secondary">hi, I am</Typography>
        <Typography
          variant="h1"
          sx={{
            letterSpacing: "3px",
          }}
        >
          JALAJ
        </Typography>
        <div>
          <Typography
            sx={{
              textAlign: "justify",
            }}
            color="text.secondary"
          >
            some thing about mesome thing about mesome thing about mesome thing
            about mesome thing about mesome thing about mesome thing about
            mesome thing about mesome thing about me
          </Typography>
          <div style={{ marginTop: "16px", textAlign: "center" }}>
            <GlowingButtonPrimary>Show me the code</GlowingButtonPrimary>
            <GlowingButton
              sx={(theme) => ({
                border: "2px solid transparent",
                ml: 2,
                [theme.breakpoints.down("md")]: {
                  ml: 0,
                  mt: 1,
                },
              })}
            >
              More about me
            </GlowingButton>
          </div>
        </div>
        <span></span>
      </Box>
      <div style={{ height: "100vh" }} />
      <div style={{ height: "100vh" }} />
      <div style={{ height: "100vh" }} />
      <div style={{ height: "100vh" }} />
    </Box>
  );
};

export default Home;
